### ISSUE TITLE
Database - First structure on strapi

### ISSUE THREAD

**Issue by MarineMontailler** [WildCodeSchool/lyon-p3-sens-interdit#17]
As developer, i need to create tables for the temporary database on strapi.

- [x] Spectacle
- [x] Festival

- [ ] Theater

- [ ] Country

- [ ] Tour

- [ ] Price (strapi component)

- [ ] Team (strapi component)

- [ ] Role Team (linked to "Team", strapi component)

- [ ] Staff

- [ ] Staff role

- [ ] user

- [ ] category

- [ ] new (changed to post)

- [ ] partner

- [ ] setting

- [ ] media

**Comment by Seblecaribou** [comment]
Let's continue our journey through this nightmarish task!

After a meet up with the client, we kind of realised that **a fully relational database was not what was needed for this project**. The client needs to be able to add whatever information needed without the cumbersome nature of adding relationship between each table. So we switched to a more malleable structure, with few direct relations between tables except those that were really needed: **festival and spectacles** (the center pieces of the website) and **a couple more tables for the recurring logos of parteners, legal obligations** etc. The rest of the collections/tables are going to be dedicated to dynamic menus.

**I'm closing this issue, now and re-opening another that describe better the task at end.**
