### ISSUE TITLE
BO FO - Press page - STRAPI/GATSBY

### ISSUE THREAD

**Issue by MarineMontailler** [WildCodeSchool/lyon-p3-sens-interdit#31]
As user, i want a beautiful design on the website

[update] 
This issue is now about:
1/ creating a SINGLE TYPE in Strapi that contains **a tab_element (repeatable)**, and **a text for the description** of the page (see image below in the comment)

2/ displaying the data in Gatsby using graphQL.

**Comment by Seblecaribou** [comment]
![](https://i.imgur.com/Q3X4tNT.jpg)
