### ISSUE TITLE
Verification : comment code

### ISSUE THREAD

**Issue by MarineMontailler** [WildCodeSchool/lyon-p3-sens-interdit#36]
As developer, i need to check if the code is well commented in order to transfer the project at the next company.

**Comment by Seblecaribou** [comment]
[UPDATE]

Commenting too much of the code might not be the best solution: it's not always explicit enough, it doesn't provide all of the options to the person modifying the app, and it doesn't really express the links between things.

So I asked the team, and had a positive feedback on it, and we are not going to comment our code; we are going to do better than that: a comprehensive wiki in this repository.

Starting from today, I will compile every major aspect of the app that deserve explanation in the wiki section of this repository, with a special focus on the components we used in Gatsby JS, and the structure we created in Strapi for the admin users.

I close this issue and open a new one, about the wiki.
