### ISSUE TITLE
FO - Spectacles Page link to ticket office

### ISSUE THREAD

**Issue by justinehell** [WildCodeSchool/lyon-p3-sens-interdit#43]
As a user, I want to buy a ticket for a spectacle
- [ ] link to buy ticket

**Comment by Seblecaribou** [comment]
For this issue we are refering to two different buttons:

The first on the red banner in the slider:
![](https://i.imgur.com/8DvqiVs.jpg)

The second on the calendar under the slider:
![](https://i.imgur.com/3G69e6h.jpg)

Where do they lead? First one is to determine, but  the second leads to that spectacle at that date.

**Comment by ShivanPaishari** [comment]
Hello, j'ai ajouté le lien principal vers Mapado( dans le header). 
il faut attendre d'avoir les datas des spectacles qui fonctionnent pour faire les liens spécifiques
