### ISSUE TITLE
FO - Architecture Header React Component - Title / logo

### ISSUE THREAD

**Issue by justinehell** [WildCodeSchool/lyon-p3-sens-interdit#44]
As user, I want to see the website title 

- The title/logo is a link that redirect to the Home Page 
- The date of the next festival

**Comment by Seblecaribou** [comment]
The logo is in place, and the date too. **It needs to be linked to a Strapi Global Setting Page or Header Setting Page**. I'm closing this issue and making a new one about the Strapi end of this component.
