### ISSUE TITLE
FO - Spectacle - integrating the calendar component - GATSBY

### ISSUE THREAD

**Issue by ShivanPaishari** [WildCodeSchool/lyon-p3-sens-interdit#62]
As a user, i would like to see all the dates of the representations in a calendar
the content of  component will be done in another US.

**Comment by Seblecaribou** [comment]
After seeing the mockup given to us, we realised that the calendar is actually three different variations on the same concept.

"Hors Scène":
![blablab](https://i.imgur.com/6YRahGv.jpg)

Spectacle:
![blabla](https://i.imgur.com/Tq3agUF.jpg)

Home:
![blabal](https://i.imgur.com/I4LDXbn.jpg)

**Hors Scene and Spectacle are roughly the same**, except for the content they dispay (they probably will be the same gatsby component in the end.
As for Festival, it spans over the month the festival takes place.
