### ISSUE TITLE
FO -  Hors Scène page

### ISSUE THREAD

**Issue by ShivanPaishari** [WildCodeSchool/lyon-p3-sens-interdit#66]
[update]
This issue is about:
1/ creating a **SINGLE TYPE** in Strapi, that contains a **rich-text field for the desciption** of the page, a **tab_element component (repeatable)**

2/ displaying it in the corresponding Gatsby page as shown in the image in the comment section.

**Comment by Seblecaribou** [comment]
![blabla](https://i.imgur.com/mqL8ypL.jpg)

**Comment by ShivanPaishari** [comment]
Page commencée avec les données en dur. Il faut attendre que les datas des spectacles fonctionnent pour avancer = query + étiquettes spectacles
