### ISSUE TITLE
FO - Hors Scene - Calendar Creation

### ISSUE THREAD

**Issue by justinehell** [WildCodeSchool/lyon-p3-sens-interdit#67]
Creation of global module calendar 

- today's date must be in red
- on the touring show page (page spectacle en tournée), the calendar displays the months and not the days

Notes : inspiration [Karavel Website](https://karavel.karavelkalypso.com/)

**Comment by Seblecaribou** [comment]
HORS SCENE: 
![blablab](https://i.imgur.com/6YRahGv.jpg)
