### ISSUE TITLE
Design - Programmation Page

### ISSUE THREAD

**Issue by Seblecaribou** [WildCodeSchool/lyon-p3-sens-interdit#92]
![](https://i.imgur.com/KUJfHUm.jpg)

**Comment by MarineMontailler** [comment]
Il reste à faire : 
- Filtres
- Toutes les connexions avec le Back Strapi
- Calendrier fonctionnel

**Comment by Seblecaribou** [comment]
I'll close this issue and open a new one about strapi and the calendar component.
